---
- name: Installation des composants Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Suppression de l'ancienne définition du dépôt Kubernetes (legacy apt_repository)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/kubernetes.list
        - /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Ajout du dépôt Kubernetes
      deb822_repository:
        name: kubernetes
        types: deb
        uris: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_version }}/deb/"
        suites: /
        signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_version }}/deb/Release.key"
        state: present

    - name: Installation des paquets Kubernetes
      apt:
        name: "{{ kubernetes_packages | map('regex_replace', '$', '=' + kubernetes_version + '-*') | list }}"
        state: present
        update_cache: yes

    - name: Empêcher la mise à jour automatique des paquets Kubernetes
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ kubernetes_packages }}"

    - name: Installation de cri-tools (crictl)
      apt:
        name: cri-tools
        state: present

    - name: Empêcher la mise à jour automatique de cri-tools
      dpkg_selections:
        name: cri-tools
        selection: hold

    - name: Activation du service kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Ajouter l'utilisateur vagrant au groupe root
      user:
        name: vagrant
        groups: root
        append: yes
    
    - name: Configuration de crictl
      shell: crictl config runtime-endpoint unix:///run/containerd/containerd.sock
      changed_when: false

    - name: Recharger le daemon systemd
      systemd:
        daemon_reload: yes

    - name: Configuration de la completion Bash pour kubectl
      lineinfile:
        path: "{{ ansible_facts['user_dir'] }}/.bashrc"
        line: "source <(kubectl completion bash)"
        state: present
        create: yes
