---
- name: Ajout des masters additionnels
  hosts: masters:!primary_master
  become: true
  tasks:
    - name: Jointure du cluster en tant que master
      command: "{{ hostvars['localhost']['k8s_join_command'] }} --control-plane --certificate-key {{ hostvars['localhost']['k8s_cert_key'] }} --apiserver-advertise-address={{ ansible_host }}"
      register: join_result
      failed_when: join_result.rc != 0 and "already exists" not in join_result.stderr
      changed_when: join_result.rc == 0
      async: 300  # 5 minutes
      poll: 10    # Vérifier toutes les 10 secondes


    - name: Création du répertoire .kube pour l'utilisateur
      file:
        path: "{{ ansible_facts['user_dir'] }}/.kube"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copie du fichier de configuration admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_facts['user_dir'] }}/.kube/config"
        owner: vagrant
        group: vagrant
        remote_src: yes
        mode: '0644'
